language: java

jdk:
  - oraclejdk8

script: 
  - ./gradlew check
  - ./gradlew javadoc

deploy:
  provider: pages
  local_dir: build/docs/javadoc
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master
